# Generated by Django 4.2.1 on 2023-05-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_tarefa_tarefa_dependente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='nome',
            field=models.CharField(default='Sem nome', verbose_name=20),
        ),
    ]
